# Generated by Django 3.2.4 on 2021-12-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Videos', '0004_rename_name_album_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
