# Generated by Django 3.2.4 on 2021-12-11 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Videos', '0005_album_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='slug',
        ),
    ]
