# Generated by Django 3.2.4 on 2021-12-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Videos', '0006_remove_album_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='thumbnail',
            field=models.ImageField(default=False, null=True, upload_to=''),
        ),
    ]
