# Generated by Django 3.2.4 on 2021-12-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_alter_usermembership_user'),
        ('Videos', '0009_alter_music_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='allowed_memberships',
            field=models.ManyToManyField(to='membership.Membership'),
        ),
    ]
